apiVersion: apps/v1
kind: Deployment
metadata:
 name: httpd-frontend
spec:
 replicas: 0
 selector:
  matchLabels:
   app: httpd-frontend
 template:
  metadata:
   name: httpd-frontend
   labels:
    app: httpd-frontend
  spec:
    containers:
    - name: alpine
      image: httpd:2.4-alpine